"""
Django settings for chatbot_project project.

This file configures all Django settings for the Twin Health Chatbot project.
It relies on environment variables loaded from a .env file for security and
environment-specific configuration (e.g., SECRET_KEY, DEBUG, API Keys).

Generated by 'django-admin startproject' using Django 5.0.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# Security settings
# NOTE: Using sensible defaults (like 'False' for DEBUG) is good practice.
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS for security. Fetches a comma-separated string from the environment
# and converts it into a list.
# IMPORTANT: This line is correct for dynamic host configuration.
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat', # Your application
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chatbot_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Ensure this directory exists if you want base templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chatbot_project.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation - Standard Django settings, looks good.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    # Ensures Django looks in 'chat/static' for assets
    os.path.join(BASE_DIR, 'chat/static'),
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session configuration - These additions are excellent for persistence.
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400
SESSION_SAVE_EVERY_REQUEST = True

# ----------------------------------------------------
# 💥 CRITICAL CORRECTION: LLM Configuration
# ----------------------------------------------------

# Define the provider
LLM_PROVIDER = os.getenv('LLM_PROVIDER', 'Gemini') # Default to Gemini if not set

# Get the API key based on the provider chosen above.
# This makes sure the correct environment variable is read.
if LLM_PROVIDER == 'OpenAI':
    # Reads the key named OPENAI_API_KEY from .env
    LLM_API_KEY = os.getenv('OPENAI_API_KEY')
    LLM_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4o-mini')
elif LLM_PROVIDER == 'Gemini':
    # Reads the key named GEMINI_API_KEY from .env
    LLM_API_KEY = os.getenv('GEMINI_API_KEY')
    LLM_MODEL = os.getenv('GEMINI_MODEL', 'gemini-2.5-flash')
else:
    # Fallback/Error handling for unsupported provider
    LLM_API_KEY = None
    LLM_MODEL = None
    print(f"WARNING: Unsupported LLM_PROVIDER: {LLM_PROVIDER}")


# DEBUGGING (Remember to remove for production!)
# print(f"DEBUG: LLM_PROVIDER: {LLM_PROVIDER}")
# print(f"DEBUG: LLM_MODEL: {LLM_MODEL}")
# print(f"DEBUG: LLM_API_KEY is set: {bool(LLM_API_KEY)}")
# if LLM_API_KEY:
#     print(f"DEBUG: Value start: {LLM_API_KEY[:5]}...")
